name: Update Serial Number

on:
  push:
    branches:
      - main
    paths:
      - "**.json"

jobs:
  update-serial:
    # Skip running if the push was from our bot to avoid infinite loops
    if: github.actor != 'version-update-bot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.VERSION_UPDATE_BOT_ID }}
          private-key: ${{ secrets.VERSION_UPDATE_BOT_SECRET }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Make script executable
        run: chmod +x scripts/update-serial.sh

      - name: Update Serial Numbers
        id: update
        run: |
          CHANGES_MADE=$(./scripts/update-serial.sh)
          echo "changes_made=$CHANGES_MADE" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.update.outputs.changes_made == 'true'
        run: |
          git config user.name "Version Update Bot[bot]"
          git config user.email "version-update-bot@users.noreply.github.com"
          git commit -m "Update serial numbers in changed files"
          git push
